Repository Sakuten/backend, pull requests merged in 2018-07, with the labels that each got.

#40 Fix: Fix to use same secret_key in all dynos of Heroku
  api/config.py
  app.json
Labels: immediate

#46 Add: Auto install dependencies
  Dockerfile.dev
  Pipfile
  Pipfile.lock
Labels: immediate

#49 Add Docstrings to existing codes.
  api/app.py
  api/auth.py
  api/models.py
  api/routes/api.py
  api/routes/auth.py
  docs/uml/api-models_class.uml
  docs/uml/app_flow.uml
Labels: low priority

#43 Fix: Accept trailing slash
  api/app.py
  test/test_misc.py
Labels: bug

#57 editorconfig for backend - PR from #52
  .editorconfig
Labels: enhancement

#56 エンドポイントの再構築 -PR from #29
  api/app.py
  api/auth.py
  api/models.py
  api/routes/api.py
  api/routes/auth.py
  api/schemas.py
  api/spec/routes/api/classrooms.yml
  api/spec/routes/api/classrooms/idx.yml
  api/spec/routes/api/lotteries/apply.yml
  api/spec/routes/api/lotteries/cancel.yml
  api/spec/routes/api/lotteries/draw.yml
  api/spec/routes/api/lotteries/idx.yml
  api/spec/routes/api/status.yml
  api/spec/template.yml
  test/test_lottery.py
  test/test_user.py
  test/utils.py
Labels: enhancement, immediate

#71 Add /applications endpoints (#65)
  api/routes/api.py
  api/spec/routes/api/applications.yml
  api/spec/routes/api/applications/cancel.yml
  api/spec/routes/api/applications/idx.yml
  test/test_lottery.py
  test/utils.py
Labels: enhancement

#73 QRコードカード作成
  .gitignore
  Pipfile
  Pipfile.lock
  cards-print/Makefile
  cards-print/cards.py
  cards-print/mkhtml.py
  cards-print/mkqr.py
  cards-print/template/cards.html.j2
Labels: enhancement

#54 reCAPTCHA対応
  api/app.py
  api/config.py
  api/models.py
  api/routes/auth.py
  api/spec/definitions/Certificate.yml
  api/spec/definitions/Password.yml
  api/spec/definitions/Username.yml
  api/spec/routes/api/status.yml
  api/spec/template.yml
  test/test_lottery.py
  test/test_user.py
  test/utils.py
Labels: enhancement

#75 Add: Add RECAPTCHA_SECRET_KEY to app.json
  app.json
Labels: bug, difficult to reproduce

#77 複数人当選するようにする #66
  api/config.py
  api/routes/api.py
  test/test_lottery.py
Labels: enhancement, epic

#82 PR: IDリストの作成機能と読み込み機能
  cards-print/id.py
Labels: enhancement

#84 Change: Migrate to SecretID/PublicID based authenication
  .gitignore
  api/app.py
  api/auth.py
  api/config.py
  api/models.py
  api/routes/auth.py
  api/schemas.py
  api/spec/template.yml
  cards/Makefile
  cards/cards.py
  cards/id.py
  cards/mkhtml.py
  cards/mkid.py
  cards/mkqr.py
  cards/template/cards.html.j2
  cards/test_users.json
  test/conftest.py
  test/test_lottery.py
  test/test_user.py
  test/utils.py
Labels: enhancement

#83 創作展終了時にトークン失効
  api/auth.py
  test/test_misc.py
Labels: enhancement

#88 Add: Preview deploy configuration
  api/config.py
  api/swagger.py
Labels: bug, difficult to reproduce, enhancement

#85 Delete: Delete NobodyIsApplyingError #80
  api/draw.py
  api/routes/api.py
  api/spec/routes/api/draw_all.yml
  api/spec/routes/api/lotteries/draw.yml
Labels: bug, small

#92 Add: Add coverage reporting in .travis.yml
  .travis.yml
Labels: enhancement, low priority, small

#96 抽選に応募できる時間を制限する-#1
  api/routes/api.py
  api/spec/routes/api/lotteries/apply.yml
  test/test_lottery.py
Labels: enhancement
