Repository Sakuten/backend, pull requests merged in 2018-09, with the labels that each got.

#142 `apply`のエラーレスポンスから、`already done`を削除する
  api/draw.py
  api/routes/api.py
  api/spec/routes/api/draw_all.yml
  api/spec/routes/api/lotteries/apply.yml
  api/spec/routes/api/lotteries/cancel.yml
  api/spec/routes/api/lotteries/draw.yml
  test/test_lottery.py
Labels: refactoring

#151 `/public_id`エンドポイントのspecに`security`を追加
  api/spec/routes/api/translate_secret_to_public.yml
Labels: docs, small

#149 /ids_hashエンドポイントの追加-#91
  api/routes/api.py
  api/spec/routes/api/ids_hash.yml
  api/utils.py
  test/test_misc.py
Labels: enhancement

#144 1日目に使用されたuser idを2日目に無効化-#78
  api/app.py
  api/auth.py
  api/config.py
  api/models.py
  api/routes/api.py
  api/routes/auth.py
  cards/test_users.json
  test/conftest.py
  test/test_user.py
  test/utils.py
Labels: enhancement

#159 Filter available lotteries `/lotteries/available`
  api/routes/api.py
  api/spec/routes/api/lotteries/available.yml
  test/test_lottery.py
Labels: enhancement

#141 Fix: Add a unique constraint on user_id
  api/models.py
  api/routes/api.py
  test/test_lottery.py
Labels: bug, immediate, investigation required

#153 Use recaptcha 3
  api/config.py
  api/routes/auth.py
Labels: enhancement

#160 Deployment support
  Dockerfile
  api/app.py
  api/config.py
Labels: enhancement

#154 Manage errors using error codes
  api/app.py
  api/auth.py
  api/config.py
  api/error.py
  api/models.py
  api/routes/api.py
  api/routes/auth.py
  api/schemas.py
  errors.json
  test/test_checker.py
  test/test_error.py
  test/test_lottery.py
  test/test_user.py
Labels: enhancement

#169 Provide options to control DB initialization ways
  Dockerfile
  api/app.py
  api/config.py
  test/test_db_generate.py
  test/test_db_init.py
Labels: enhancement, epic, immediate

#172 Enhance Dockerfile
  Dockerfile
Labels: enhancement

#174 Add: Add postgresql runtime library in image
  Dockerfile
Labels: bug

#171 団体応募の上限を4人までに制限-164
  api/routes/api.py
  errors.json
  test/conftest.py
  test/test_lottery.py
  test/utils.py
Labels: enhancement, immediate

#187 /public_idエンドポイントのレスポンスのpublic_idをエンコード
  api/routes/api.py
  test/test_user.py
Labels: bug, immediate, small

#175 Lottery_schemaに`end_of_drawing`追加
  api/schemas.py
Labels: enhancement

#188 `User_schema`に'kind'追加-#186
  api/schemas.py
Labels: small

#194 `get_prev_time_index`追加-#193
  api/time_management.py
  test/test_time.py
Labels: enhancement, small

#196 Change: Add a checker to login_required list
  api/routes/api.py
Labels: bug

#197 /healthエンドポイントの雛形の追加
  api/routes/api.py
  api/spec/routes/api/health.yml
Labels: enhancement, small

#207 `/health`スペックの`response`フィールドの修正
  api/spec/routes/api/health.yml
Labels: bug, small

#208 test_users.jsonのauthorityとkindの矛盾を修正
  cards/test_users.json
Labels: bug, small

#205 `get_prev_time_index`の挙動を修正
  api/time_management.py
  test/test_time.py
Labels: bug, small

#157 scripts/draw.pyで`ids.json`のハッシュ確認をした
  scripts/draw.py
Labels: enhancement, small

#212 `/render_results`エンドポイントの追加
  Pipfile.lock
  api/config.py
  api/routes/api.py
  api/spec/routes/api/results.yml
  api/templates/results.html
  scripts/apply_ramdom.py
  scripts/draw_all.py
Labels: enhancement

#214 Get time-related configs from environment variable in production environment
  api/config.py
Labels: enhancement

#218 劇の名前をクラスに紐付ける
  api/app.py
  api/config.py
  api/models.py
  api/schemas.py
  classrooms.json
Labels: enhancement

#230 `is_member`の追加
  api/schemas.py
  test/test_schema.py
Labels: request from frontend
