Repository Sakuten/backend, pull requests merged in 2018-08, with the labels that each got.

#89 Add: Add a standalone draw script
  api/routes/auth.py
  scripts/draw.py
Labels: enhancement

#64 Lotteryモデルのdocstring変更
  api/models.py
Labels: docs, investigation required

#110 /lotteries/{id}/drawの条件分岐を直した-#107
  api/routes/api.py
  test/test_lottery.py
Labels: bug

#130 Bugfix: many qrs not printed
  cards/Makefile
  cards/mkhtml.py
Labels: bug

#120 複数人の *抽選*
  api/draw.py
  api/models.py
  api/schemas.py
  api/spec/template.yml
  docs/uml/api-models_class.uml
  test/test_lottery.py
Labels: enhancement

#134 `/status`エンドポイントの仕様書を書き直した - #133
  api/spec/template.yml
Labels: docs

#111 応募期間に一分間の猶予を追加-#95
  api/config.py
  api/time_management.py
  test/test_lottery.py
  test/test_time.py
Labels: enhancement, small

#127 団体応募
  api/models.py
  api/routes/api.py
  api/spec/routes/api/lotteries/apply.yml
  api/spec/template.yml
  test/conftest.py
  test/test_lottery.py
  test/utils.py
Labels: enhancement

#131 当選者発表用API`/lotteries/{id}/winners`の追加
  api/models.py
  api/routes/api.py
  api/spec/routes/api/lotteries/winners.yml
  test/test_lottery.py
Labels: enhancement, small

#136 `/public_id`追加-#126
  api/routes/api.py
  api/spec/routes/api/translate_secret_to_public.yml
  test/test_user.py
Labels: enhancement

#140 PULL_REQUEST_TEMPLATE.mdの書き直し-#138
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs, small
